# Create artifacts folder, where all outputs of the pipeline will be stored.
# artifacts_root: artifacts

# # Data ingestion config to save important things like file paths and the dataset URL:

# data_ingestion: # Root name:
#   # Sub folders:
#   root_dir: artifacts/data_ingestion
#   source_URL: https://github.com/parichehrma/Text-Summarizer/raw/refs/heads/main/samsumdata.zip
#   local_data_file: artifacts/data_ingestion/data.zip
#   unzip_dir: artifacts/data_ingestion


artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/parichehrma/Text-Summarizer/main/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
